### ISSUE TITLE
demande mise a jour de readme.md

### ISSUE THREAD

**Issue by YounessSerrakhi** [CodeVerse-IRISI/Front_AquaSonic#1]
https://github.com/CodeVerse-IRISI/Front_AquaSonic/blob/379cb1239b14b2b2ae92638adaa23dc5bc446c90/README.md?plain=1#L5

@hiba-douik

**Comment by YounessSerrakhi** [comment]
also you should either mention every file's utility  in the toot in the readme, if it's without utility -> delete

**Comment by hiba-douik** [comment]
done
